[package]
name = "tyme-db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tyme-utils = { path = "../tyme-utils" }
anyhow = { version = "1.0.71", features = ["backtrace"] }
log = "0.4.18"
tokio = { version = "1.28.2", features = ["full"] }
chrono = { version = "0.4.25", features = ["serde"] }
uuid = { version = "1.3.3", features = ["v4", "serde"] }
serde = "1.0.163"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend",
]

[dependencies.sqlx]
version = "0.6"
features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "uuid",
    "chrono",
    "tls",
]

[dependencies.chrono-tz]
version = "0.8.2"
features = ["std", "case-insensitive", "serde"]
