[package]
name = "tyme-db"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
chrono = "0.4.26"

[dependencies.diesel]
features = ["mysql", "chrono"]
version = "2.1.0"

[dependencies.chrono-tz]
features = ["std", "case-insensitive"]
version = "0.8.2"
