[package]
name = "tyme-db"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
tyme-utils = { path = "../tyme-utils" }

anyhow = { version = "1.0.71", features = ["backtrace"] }
chrono = { version = "0.4.26", features = ["serde"] }
log = "0.4.18"
tokio = { version = "1.28.2", features = ["full"] }

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend",
    "chrono",
    "interactions_endpoint",
]

[dependencies.sqlx]
version = "0.6.3"
features = [
    "runtime-tokio-rustls",
    "mysql",
    "macros",
    "migrate",
    "chrono",
]

[dependencies.chrono-tz]
version = "0.8.2"
features = ["std", "case-insensitive", "serde"]
