[package]
name = "tyme"
version = "0.1.0"
authors = ["erics118"]
edition = "2021"
rust-version = "1.65.0"
description = "A discord bot to manage reminders"
repository = ""
license = "MIT"
keywords = ["discord", "reminder"]
categories = []
publish = false

[dependencies]
anyhow = "1.0.68"
async-anyhow-logger = "0.1.0"
dotenvy = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
serenity = { version = "0.11.5", default-features = false, features = ["builder", "cache", "client", "gateway","http", "model", "utils", "rustls_backend"]}
tokio = { version = "1.23.1", features = ["full"] }

