[package]
name = "tyme-discord"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
tyme-db = { path = "../tyme-db" }

anyhow = { version = "1.0.71", features = ["backtrace"] }
chrono = "0.4.26"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full"] }

[dependencies.serenity]
branch = "next"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "chrono"]
git = "https://github.com/serenity-rs/serenity"

[dependencies.chrono-tz]
features = ["std", "case-insensitive"]
version = "0.8.2"
