[package]
name = "tyme"
version = "0.1.0"
authors = ["erics118"]
edition = "2021"
rust-version = "1.68.0"
description = "A reminder service"
repository = "https://github.com/erics118/tyme"
license = "MIT"
keywords = ["reminder"]
categories = []
publish = false

[dependencies]
